import AppKit
import Carbon.HIToolbox
import MurmurKit

/// NSPasteboard adapted to MurmurKit's `Clipboard`, so the insert sequence is unit-testable.
struct SystemPasteboard: Clipboard {
    private let board = NSPasteboard.general

    var changeCount: Int { board.changeCount }

    func snapshot() -> [[String: Data]] {
        (board.pasteboardItems ?? []).map { item in
            Dictionary(item.types.compactMap { type in item.data(forType: type).map { (type.rawValue, $0) } },
                       uniquingKeysWith: { first, _ in first })
        }
    }

    func write(_ text: String) {
        board.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        // nspasteboard.org convention: clipboard managers skip transient and
        // auto-generated items, so dictations don't pile up in their history.
        item.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))
        item.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))
        board.writeObjects([item])
    }

    func restore(_ items: [[String: Data]]) {
        board.clearContents()
        board.writeObjects(items.map { types in
            let item = NSPasteboardItem()
            for (type, data) in types { item.setData(data, forType: NSPasteboard.PasteboardType(type)) }
            return item
        })
    }
}

enum TextInserter {
    /// Pastes (or types) `text` into the frontmost app. Returns as soon as the
    /// text is sent; the clipboard is restored in the background.
    /// - Returns: false when Accessibility is missing; the text is then left
    ///   on the clipboard for the user to paste.
    @MainActor
    static func insert(_ text: String, restoreClipboard: Bool) async -> Bool {
        let text = sanitizeForInsertion(text)
        let board = SystemPasteboard()
        guard Permissions.canPaste else {
            board.write(text)
            return false
        }
        await waitForModifiersReleased()
        let app = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        if InsertMethod.choose(bundleID: app, secureInput: IsSecureEventInputEnabled()) == .type {
            type(text)
        } else {
            Task {
                await PasteSequence.insert(text, into: board, restoreAfter: restoreClipboard ? restoreDelay(text) : nil,
                                           paste: sendCommandV)
            }
        }
        return true
    }

    /// Busy apps (Electron, VMs, remote desktops) can read the pasteboard late; restoring
    /// too early would paste the old clipboard. Longer text takes longer to land.
    static func restoreDelay(_ text: String) -> Duration {
        .milliseconds(1000 + min(text.count, 4000) / 4)
    }

    private static func type(_ text: String) {
        let source = CGEventSource(stateID: .combinedSessionState)
        for chunk in InsertMethod.typingChunks(text) {
            let units = Array(chunk.utf16)
            for keyDown in [true, false] {
                let event = CGEvent(keyboardEventSource: source, virtualKey: 0, keyDown: keyDown)
                event?.keyboardSetUnicodeString(stringLength: units.count, unicodeString: units)
                event?.flags = [] // a still-held ⌘ would turn letters into shortcuts
                event?.post(tap: .cghidEventTap)
            }
        }
    }

    private static func sendCommandV() {
        let source = CGEventSource(stateID: .combinedSessionState)
        for keyDown in [true, false] {
            let event = CGEvent(keyboardEventSource: source, virtualKey: CGKeyCode(kVK_ANSI_V), keyDown: keyDown)
            event?.flags = .maskCommand
            event?.post(tap: .cghidEventTap)
        }
    }

    /// In tap mode the user may still be holding ⌃⌥⌘ from the stop press, and
    /// the target app would see ⌃⌥⌘V. Wait (briefly) for them to let go.
    private static func waitForModifiersReleased() async {
        let held: CGEventFlags = [.maskControl, .maskAlternate, .maskCommand, .maskShift]
        var waited = 0
        while waited < 40, !CGEventSource.flagsState(.combinedSessionState).intersection(held).isEmpty {
            try? await Task.sleep(for: .milliseconds(25))
            waited += 1
        }
    }
}
