import AppKit
import Carbon.HIToolbox
import VozKit

/// NSPasteboard adapted to VozKit's `Clipboard`, so the insert sequence is unit-testable.
struct SystemPasteboard: Clipboard {
    private let board = NSPasteboard.general

    var changeCount: Int { board.changeCount }

    func snapshot() -> [[String: Data]] {
        (board.pasteboardItems ?? []).map { item in
            Dictionary(item.types.compactMap { type in item.data(forType: type).map { (type.rawValue, $0) } },
                       uniquingKeysWith: { first, _ in first })
        }
    }

    func write(_ text: String) {
        board.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        // nspasteboard.org convention: clipboard managers skip transient and
        // auto-generated items, so dictations don't pile up in their history.
        item.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))
        item.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))
        board.writeObjects([item])
    }

    func restore(_ items: [[String: Data]]) {
        board.clearContents()
        board.writeObjects(items.map { types in
            let item = NSPasteboardItem()
            for (type, data) in types { item.setData(data, forType: NSPasteboard.PasteboardType(type)) }
            return item
        })
    }
}

enum TextInserter {
    /// Pastes `text` into the frontmost app.
    /// - Returns: false when Accessibility is missing; the text is then left
    ///   on the clipboard for the user to paste.
    @MainActor
    static func insert(_ text: String, restoreClipboard: Bool) async -> Bool {
        let board = SystemPasteboard()
        guard Permissions.canPaste else {
            board.write(text)
            return false
        }
        await waitForModifiersReleased()
        await PasteSequence.insert(text, into: board, restoreAfter: restoreClipboard ? .milliseconds(500) : nil,
                                   paste: sendCommandV)
        return true
    }

    private static func sendCommandV() {
        let source = CGEventSource(stateID: .combinedSessionState)
        for keyDown in [true, false] {
            let event = CGEvent(keyboardEventSource: source, virtualKey: CGKeyCode(kVK_ANSI_V), keyDown: keyDown)
            event?.flags = .maskCommand
            event?.post(tap: .cghidEventTap)
        }
    }

    /// In tap mode the user may still be holding ⌃⌥⌘ from the stop press, and
    /// the target app would see ⌃⌥⌘V. Wait (briefly) for them to let go.
    private static func waitForModifiersReleased() async {
        let held: CGEventFlags = [.maskControl, .maskAlternate, .maskCommand, .maskShift]
        var waited = 0
        while waited < 40, !CGEventSource.flagsState(.combinedSessionState).intersection(held).isEmpty {
            try? await Task.sleep(for: .milliseconds(25))
            waited += 1
        }
    }
}
